import Head from "next/head";
import { useRouter } from "next/router";
import { useCallback, useEffect } from "react";
import { ApolloClient, InMemoryCache, ApolloProvider, gql } from '@apollo/client';

export default function article() {
    const router = useRouter();
    const { id } = router.query;

    const client = new ApolloClient({
        uri: '/api/graphql',
        cache: new InMemoryCache(),
    });

    const getArticles = useCallback(() => {
        // const client = ...

        client
            .query({
                query: gql`
      query GetBooks {
        books {
          title
          author
        }
      }
    `,
            })
            .then((result) => console.log(result));
    }, []);

    useEffect(() => {
        getArticles();
    });

    return (
        <div>
            <Head>
                <title>Article</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                Article ID: { id }
            </main>
        </div>
    )
}